sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "5.0"
before_install:
# Get installer script.
  - cd bin
  - wget https://github.com/nodeGame/nodegame/raw/master/bin/install-nodegame-for-module.sh
  - chmod a+x install-nodegame-for-module.sh
  - cd ..
install:
# Share node_modules with nodeGame.
  - mkdir -p nodegame node_modules
#  - ln -s ../node_modules nodegame/node_modules
#  - ln -s .. node_modules/nodegame-client
  - bin/install-nodegame-for-module.sh -g "nodegame-window nodegame-widgets JSUS NDDB shelf.js nodegame-server descil-mturk nodegame-requirements nodegame-monitor nodegame-db nodegame-mongodb"
  - npm install
  - ln -s ../.. nodegame/node_modules/nodegame-client
script:
# nodegame-client tests here.
  - npm test
# Test Ultimatum game.
  - cd nodegame/games
  - git clone https://github.com/nodeGame/ultimatum.git
  - cd ultimatum
  - ./bin/run-standalone-test.sh
